--商品分类
INSERT INTO t_comm_category(ID, CATEGORY_CODE, CATEGORY_NAME, CREATE_TIME, LAST_MODIFIER, LAST_MODIFIED, STATUS) 
    VALUES(1,'0000100001', '商务套餐', now(), 'ROOT', now(), 0);
INSERT INTO t_comm_category(ID, CATEGORY_CODE, CATEGORY_NAME, CREATE_TIME, LAST_MODIFIER, LAST_MODIFIED, STATUS) 
    VALUES(2,'0000100002', '快捷简餐', now(), 'ROOT', now(), 0);

--供应商
INSERT INTO t_comm_provider(PROVIDER_CODE, PROVIDER_NAME, PROVIDER_DESCRIBE, CONTACTOR, MOBILE, ADDRESS, CREATE_TIME, LAST_MODIFIER, LAST_MODIFIED, STATUS) 
    VALUES('0000100001', '咱家小院', '咱家小院介绍', '张三', '13815421625', '南京市玄武区鹤鸣路101号', now(), 'ROOT', now(), 0);

--商品
INSERT INTO t_commidity(COM_ID, COM_NAME, PROVIDER_ID, CATEGORY_ID, COM_DESCRIBE, CREATE_TIME, LAST_MODIFIER, LAST_MODIFIED, STATUS) 
    VALUES('0000100001000010000100001', '鱼香肉丝盖浇饭', 1, 1, '鱼香肉丝盖浇饭介绍', now(), 'ROOT', now(), 0);
INSERT INTO t_commidity(COM_ID, COM_NAME, PROVIDER_ID, CATEGORY_ID, COM_DESCRIBE, CREATE_TIME, LAST_MODIFIER, LAST_MODIFIED, STATUS) 
    VALUES('0000100001000010000100002', '鱼香肉丝煲', 1, 1, '鱼香肉丝煲介绍', now(), 'ROOT', now(), 0);
GO

