package com.myit.server.model.business;

// Generated 2013-7-17 20:13:43 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import com.myit.common.beans.BaseModel;

/**
 * TBusinessBusinessifo generated by hbm2java
 */
public class BusinessInfo extends BaseModel {

    /**
     */
    private static final long serialVersionUID = 1072341099832887204L;

    private String businessNo;

    private String businessName;

    private int provienceId;

    private int cityId;

    private int countyId;

    private String address;

    public BusinessInfo() {
    }

    public BusinessInfo(String businessNo, String businessName, Date createTime, Date lastModified, int provienceId,
            int cityId, int countyId, String address, String statu) {
        this.businessNo = businessNo;
        this.businessName = businessName;
        this.provienceId = provienceId;
        this.cityId = cityId;
        this.countyId = countyId;
        this.address = address;

        this.setCreateTime(createTime);
        this.setLastModified(lastModified);
        this.setStatus(statu);
    }

    public String getBusinessNo() {
        return this.businessNo;
    }

    public void setBusinessNo(String businessNo) {
        this.businessNo = businessNo;
    }

    public String getBusinessName() {
        return businessName;
    }

    public void setBusinessName(String businessName) {
        this.businessName = businessName;
    }

    public int getProvienceId() {
        return this.provienceId;
    }

    public void setProvienceId(int provienceId) {
        this.provienceId = provienceId;
    }

    public int getCityId() {
        return this.cityId;
    }

    public void setCityId(int cityId) {
        this.cityId = cityId;
    }

    public int getCountyId() {
        return this.countyId;
    }

    public void setCountyId(int countyId) {
        this.countyId = countyId;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Override
    public String toString() {
        return "BusinessInfo [businessNo=" + businessNo + ", businessName=" + businessName + ", provienceId="
                + provienceId + ", cityId=" + cityId + ", countyId=" + countyId + ", address=" + address + "]";
    }

}
