package com.myit.server.model.business;

// Generated 2013-7-17 20:13:43 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import com.myit.common.beans.BaseModel;

/**
 * TBusinessShipping generated by hbm2java
 */
public class BusinessShipping extends BaseModel {

    /**
     */
    private static final long serialVersionUID = -2542896421634758724L;

    /** 商户id **/
    private int businessId;

    /** 位置id **/
    private int locationId;

    /** 地址 **/
    private String address;

    public BusinessShipping() {
    }

    public BusinessShipping(int businessId, int locationId, String address, Date createTime, Date lastModified,
            String statu) {
        this.businessId = businessId;
        this.locationId = locationId;
        this.address = address;

        this.setCreateTime(createTime);
        this.setLastModified(lastModified);
        this.setStatus(statu);
    }

    public int getBusinessId() {
        return this.businessId;
    }

    public void setBusinessId(int businessId) {
        this.businessId = businessId;
    }

    public int getLocationId() {
        return this.locationId;
    }

    public void setLocationId(int locationId) {
        this.locationId = locationId;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Override
    public String toString() {
        return "BusinessShipping [businessId=" + businessId + ", locationId=" + locationId + ", address=" + address
                + "]";
    }

}
