package com.myit.server.model.business;

// Generated 2013-7-17 20:13:43 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import com.myit.common.beans.BaseModel;

/**
 * BusinessCommoInfo generated by hbm2java
 */
public class CommoInfo extends BaseModel {

    /**
     */
    private static final long serialVersionUID = -7518139941207216258L;

    /** 商品编码 **/
    private String commoNo;

    /** 商品名称 **/
    private String commoName;

    /** 商户id **/
    private int businessId;

    /** 商品描述 **/
    private String commoDescribe;

    /** 结算价 **/
    private BigDecimal settlePrice;

    /** 售价 **/
    private BigDecimal sellPrice;

    public CommoInfo() {
    }

    public CommoInfo(String commoNo, String commoName, int businessId, String commoDescribe, Date createTime,
            Date lastModified, String statu, BigDecimal settlePrice, BigDecimal sellPrice) {
        this.commoNo = commoNo;
        this.commoName = commoName;
        this.businessId = businessId;
        this.commoDescribe = commoDescribe;
        this.settlePrice = settlePrice;
        this.sellPrice = sellPrice;

        this.setCreateTime(createTime);
        this.setLastModified(lastModified);
        this.setStatus(statu);
    }

    public String getCommoNo() {
        return this.commoNo;
    }

    public void setCommoNo(String commoNo) {
        this.commoNo = commoNo;
    }

    public String getCommoName() {
        return this.commoName;
    }

    public void setCommoName(String commoName) {
        this.commoName = commoName;
    }

    public int getBusinessId() {
        return this.businessId;
    }

    public void setBusinessId(int businessId) {
        this.businessId = businessId;
    }

    public String getCommoDescribe() {
        return this.commoDescribe;
    }

    public void setCommoDescribe(String commoDescribe) {
        this.commoDescribe = commoDescribe;
    }

    public BigDecimal getSettlePrice() {
        return this.settlePrice;
    }

    public void setSettlePrice(BigDecimal settlePrice) {
        this.settlePrice = settlePrice;
    }

    public BigDecimal getSellPrice() {
        return this.sellPrice;
    }

    public void setSellPrice(BigDecimal sellPrice) {
        this.sellPrice = sellPrice;
    }

    @Override
    public String toString() {
        return "BusinessCommoInfo [commoNo=" + commoNo + ", commoName=" + commoName + ", businessId=" + businessId
                + ", commoDescribe=" + commoDescribe + ", settlePrice=" + settlePrice + ", sellPrice=" + sellPrice
                + "]";
    }

}
