package com.myit.intf.bean.baseData;

// Generated 2013-7-17 20:13:43 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import com.myit.common.beans.BaseModel;

/**
 * Location generated by hbm2java
 */
public class LocationEvt extends BaseModel {

    /**
     */
    private static final long serialVersionUID = 4869794314074027957L;

    /** 省份id **/
    private Long provId;

    /** 省份名称 **/
    private String provName;

    /** 城市id **/
    private Long cityId;

    /** 城市名称 **/
    private String cityName;

    /** 区县id **/
    private Long countyId;

    /** 区县名称 **/
    private String countyName;

    public LocationEvt() {
    }

    public LocationEvt(Long provId, String provName, Long cityId, String cityName, Long countyId, String countyName,
            Date createTime, Date lastModified, String statu) {
        this.provId = provId;
        this.provName = provName;
        this.cityId = cityId;
        this.cityName = cityName;
        this.countyId = countyId;
        this.countyName = countyName;
        this.setCreateTime(createTime);
        this.setLastModified(lastModified);
        this.setStatus(statu);
    }

    public Long getProvId() {
        return this.provId;
    }

    public void setProvId(Long provId) {
        this.provId = provId;
    }

    public String getProvName() {
        return this.provName;
    }

    public void setProvName(String provName) {
        this.provName = provName;
    }

    public Long getCityId() {
        return this.cityId;
    }

    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    public String getCityName() {
        return this.cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public Long getCountyId() {
        return this.countyId;
    }

    public void setCountyId(Long countyId) {
        this.countyId = countyId;
    }

    public String getCountyName() {
        return this.countyName;
    }

    public void setCountyName(String countyName) {
        this.countyName = countyName;
    }

    @Override
    public String toString() {
        return "Location [id=" + getId() + ", provId=" + provId + ", provName=" + provName + ", cityId=" + cityId
                + ", cityName=" + cityName + ", countyId=" + countyId + ", countyName=" + countyName + ", createTime="
                + getCreateTime() + ", lastModified=" + getLastModified() + ", statu=" + getStatus() + "]";
    }

}
